/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Dogadjaj;
import domen.Nalog;
import domen.Mesto;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.MutableComboBoxModel;
import kontroler.KontrolerKI;
import modelTabela.TableModelDogadjaji;
import prenos.Odgovor;

/**
 *
 * @author Jaša
 */
public class GlavnaForma extends javax.swing.JFrame implements InterfejsOpstaEkranskaForma {

    TableModelDogadjaji tmd;
    KontrolerKI kontroler;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        kontroler = KontrolerKI.getInstance();
        kontroler.registrujGlavnuFormu(this);
        popuniTabelu(kontroler.getDogadjaji());
        popuniComboBox(kontroler.getMesta());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtKljucneReci = new javax.swing.JTextField();
        jPanelDogadjaji = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDogadjaji = new javax.swing.JTable();
        jbtnPrisustvuj = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtnNapraviDogadjaj = new javax.swing.JButton();
        jbtnPrikaziMoje = new javax.swing.JButton();
        jbtnPronadji = new javax.swing.JButton();
        jtxtIme = new javax.swing.JLabel();
        jComboBoxMesta = new javax.swing.JComboBox<>();
        jbtnOdjava = new javax.swing.JButton();
        jXDatum = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmNalog = new javax.swing.JMenu();
        jmiKreirajNalog = new javax.swing.JMenuItem();
        jmiUpravljajNalogom = new javax.swing.JMenuItem();
        jmiPrisustva = new javax.swing.JMenu();
        jMenuItemPrisustva = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Dodađaji ]");

        jtxtKljucneReci.setToolTipText("Unesi ključne reči");

        jPanelDogadjaji.setBorder(javax.swing.BorderFactory.createTitledBorder("Događaji"));

        jTableDogadjaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDogadjaji);

        jbtnPrisustvuj.setText("Prisustvuj!");
        jbtnPrisustvuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrisustvujActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDogadjajiLayout = new javax.swing.GroupLayout(jPanelDogadjaji);
        jPanelDogadjaji.setLayout(jPanelDogadjajiLayout);
        jPanelDogadjajiLayout.setHorizontalGroup(
            jPanelDogadjajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDogadjajiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDogadjajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDogadjajiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPrisustvuj)))
                .addContainerGap())
        );
        jPanelDogadjajiLayout.setVerticalGroup(
            jPanelDogadjajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDogadjajiLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDogadjajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrisustvuj)
                    .addComponent(jbtnDetalji)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtnNapraviDogadjaj.setText("Napravi događaj");
        jbtnNapraviDogadjaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNapraviDogadjajActionPerformed(evt);
            }
        });

        jbtnPrikaziMoje.setText("Prikaži moje!");
        jbtnPrikaziMoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrikaziMojeActionPerformed(evt);
            }
        });

        jbtnPronadji.setText("Pronađi");
        jbtnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPronadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnNapraviDogadjaj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbtnPrikaziMoje, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jbtnPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNapraviDogadjaj)
                    .addComponent(jbtnPrikaziMoje)
                    .addComponent(jbtnPronadji))
                .addContainerGap())
        );

        jtxtIme.setText("Ime");

        jComboBoxMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMestaActionPerformed(evt);
            }
        });

        jbtnOdjava.setText("Odjava");
        jbtnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdjavaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ključne reči:");

        jLabel2.setText("Datum od:");

        jmNalog.setText("Nalog");

        jmiKreirajNalog.setText("Kreiraj nalog");
        jmiKreirajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajNalogActionPerformed(evt);
            }
        });
        jmNalog.add(jmiKreirajNalog);

        jmiUpravljajNalogom.setText("Upravljaj nalogom");
        jmiUpravljajNalogom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUpravljajNalogomActionPerformed(evt);
            }
        });
        jmNalog.add(jmiUpravljajNalogom);

        jMenuBar1.add(jmNalog);

        jmiPrisustva.setText("Prisustva");

        jMenuItemPrisustva.setText("Prikaz prisustva");
        jMenuItemPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrisustvaActionPerformed(evt);
            }
        });
        jmiPrisustva.add(jMenuItemPrisustva);

        jMenuBar1.add(jmiPrisustva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtKljucneReci, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelDogadjaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnOdjava)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOdjava)
                    .addComponent(jtxtIme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtKljucneReci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDogadjaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUpravljajNalogomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUpravljajNalogomActionPerformed
        try {
            Odgovor odg = kontroler.pronadjiMojNalog();
            if (odg.isUspesno()) {
                JOptionPane.showMessageDialog(rootPane, odg.getPoruka());
                Nalog nalogKorisnika = (Nalog) odg.getRezultat();
                NalogForma nf = new NalogForma(this, true);
                nf.postaviNalog(nalogKorisnika);
                nf.setVisible(true);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiUpravljajNalogomActionPerformed

    private void jbtnPrikaziMojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrikaziMojeActionPerformed
        if (jbtnPrikaziMoje.getText().equalsIgnoreCase("Prikaži moje!")) {
            tmd.promeniStanje(KontrolerKI.getInstance().pronadjiMojeDogadjaje());
            jbtnPrikaziMoje.setText("Prikaži najsvežije!");
            return;

        }
        if (jbtnPrikaziMoje.getText().equalsIgnoreCase("Prikaži najsvežije!")) {
            tmd.promeniStanje(KontrolerKI.getInstance().vratiNajskorije());
            jbtnPrikaziMoje.setText("Prikaži moje!");
            return;
        }

    }//GEN-LAST:event_jbtnPrikaziMojeActionPerformed

    private void jbtnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdjavaActionPerformed
        KontrolerKI.getInstance().odjava();
    }//GEN-LAST:event_jbtnOdjavaActionPerformed

    private void jbtnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPronadjiActionPerformed
        String opis = jtxtKljucneReci.getText().trim().toLowerCase();
        Mesto m = (Mesto) jComboBoxMesta.getSelectedItem();
        System.out.println(m.getNaziv());
        Date datum = jXDatum.getDate();
        Dogadjaj d = new Dogadjaj("", "", opis, datum, "", null, null, m);
        tmd.promeniStanje(kontroler.pronadjiDogadjaje(d));
    }//GEN-LAST:event_jbtnPronadjiActionPerformed

    private void jComboBoxMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMestaActionPerformed

    private void jbtnNapraviDogadjajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNapraviDogadjajActionPerformed
        DogadjajForma df = new DogadjajForma();
        df.setVisible(true);
        df.podesiLabeluKorisnik(jtxtIme.getText());
    }//GEN-LAST:event_jbtnNapraviDogadjajActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        Dogadjaj odabraniDogadjaj = tmd.getListaDogadjaja().get(jTableDogadjaji.getSelectedRow());
        try {
            Dogadjaj dogadjaj = KontrolerKI.getInstance().prikaziDogadjaj(odabraniDogadjaj);
            DogadjajFormaPrikaz dfp = new DogadjajFormaPrikaz();
            dfp.setVisible(true);
            dfp.popuniDogadjaj(dogadjaj);
                    } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void jmiKreirajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajNalogActionPerformed
        NalogForma nf = new NalogForma(this, true);
        nf.setVisible(true);
    }//GEN-LAST:event_jmiKreirajNalogActionPerformed

    private void jbtnPrisustvujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrisustvujActionPerformed
        Dogadjaj d = tmd.getListaDogadjaja().get(jTableDogadjaji.getSelectedRow());
        PrisustvoForma pf = new PrisustvoForma(this, true);
        pf.postaviVrednosti(kontroler.getNalog(), d);
        pf.setVisible(true);
    }//GEN-LAST:event_jbtnPrisustvujActionPerformed

    private void jMenuItemPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrisustvaActionPerformed
        PrisustvaPrikaz pp = new PrisustvaPrikaz(this, true);
        pp.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrisustvaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Mesto> jComboBoxMesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPrisustva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDogadjaji;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDogadjaji;
    private org.jdesktop.swingx.JXDatePicker jXDatum;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnNapraviDogadjaj;
    private javax.swing.JButton jbtnOdjava;
    private javax.swing.JButton jbtnPrikaziMoje;
    private javax.swing.JButton jbtnPrisustvuj;
    private javax.swing.JButton jbtnPronadji;
    private javax.swing.JMenu jmNalog;
    private javax.swing.JMenuItem jmiKreirajNalog;
    private javax.swing.JMenu jmiPrisustva;
    private javax.swing.JMenuItem jmiUpravljajNalogom;
    private javax.swing.JLabel jtxtIme;
    private javax.swing.JTextField jtxtKljucneReci;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox(LinkedList<Mesto> mesta) {
        for (Mesto mesto : mesta) {
            jComboBoxMesta.addItem(mesto);
        }
        jComboBoxMesta.addItem(new Mesto("0", "Sva mesta"));
    }

    private void popuniTabelu(LinkedList<Dogadjaj> dogadjaji) {
        tmd = new TableModelDogadjaji(dogadjaji);
        jTableDogadjaji.setModel(tmd);
    }

    @Override
    public void prikaziPoruku(String poruka) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void osvezi() {
        tmd.promeniStanje(KontrolerKI.getInstance().getDogadjaji());
    }

    void setIme(String text) {
        jtxtIme.setText(text);
    }
}
